### ISSUE TITLE
linfa_bayes show error: records not in row-major layout

### ISSUE THREAD

**Issue by coolstudio1678** [rust-ml/linfa#339]
```
  let df =CsvReader::from_path("./510_model_data.csv")
            .unwrap()
            .infer_schema(None)
            .has_header(true)
            .finish()
            .unwrap();
    let df = df.tail(Some(200));
    let col_target = df.column("d_target_high").unwrap();
    let target_high = col_target.f64().unwrap().iter().collect::<Vec<_>>();
    let target: ArrayBase<ndarray::OwnedRepr<_>, _> = ArrayBase::from_vec(target_high.to_vec());
    let mut features = df.clone();
    features = features.drop("d_target_low").unwrap();
    features = features.drop("d_target_high").unwrap();

    for col_name in features.get_column_names_owned(){
        let casted_col = df.column(&col_name).unwrap()
            .cast(&DataType::Float32)
            .expect("Failed to cast column");
        features.with_column(casted_col).unwrap();        
    }

    let features_ar = features.to_ndarray::<Float64Type>(IndexOrder::Fortran).unwrap();

    let linfa_dataset = Dataset::new(features_ar,target)
           .map_targets(|x| if *x > Some(2.0) {"red"} else {"green"});
    let (train,valid) = linfa_dataset.split_with_ratio(0.9);
    let model = MultinomialNb::params().fit(&train)?;
```

thread 'main' panicked at C:\Users\44310\.cargo\registry\src\index.crates.io-6f17d22bba15001f\linfa-0.7.0\src\dataset\impl_dataset.rs:946:9:
records not in row-major layout
how to solve it?

**Comment by coolstudio1678** [comment]
`let features_ar = features.to_ndarray::<Float64Type>(IndexOrder::C).unwrap();`

change to IndexOrder::C，show errors: 

thread 'main' panicked at C:\Users\44310\.cargo\registry\src\index.crates.io-6f17d22bba15001f\linfa-bayes-0.7.0\src\base_nb.rs:44:32:
called `Result::unwrap()` on an `Err` value: UndefinedOrder
